execute pathogen#infect()

set background=dark
colorscheme solarized
let g:solarized_termtrans=1
let g:solarized_termcolors = 256
syntax on
filetype plugin indent on

" indenting
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab

" key bindings
map <C-n> :NERDTreeToggle<CR> "Ctrl + n opens nerd tree

" airline
set laststatus=2
