execute pathogen#infect()

set background=dark
colorscheme solarized
let g:solarized_termtrans=1
let g:solarized_termcolors = 256
syntax on
filetype plugin indent on

" key bindings
map <C-n> :NERDTreeToggle<CR> "Ctrl + n opens nerd tree
